FROM node:20-alpine AS build
WORKDIR /app
COPY package.json tsconfig.json .
COPY src ./src
RUN npm install --no-audit --no-fund
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
EXPOSE 4000
CMD ["node", "dist/src/server.js"]
